export const shaderPractices = {
  basicShader: () => import('./BasicShader'),
  wavesShader: () => import('./Waves'),
  galaxyShader: () => import('./Galaxy'),
  leePerryShader: () => import('./LeePerry'),
  coffeeSmokeShader: () => import('./CoffeeSmoke'),
  hologramShader: () => import('./Hologram'),
  fireworksShader: () => import('./Fireworks'),
  lightingBasicsShader: () => import('./LightingBasics'),
  halftoneShader: () => import('./Halftone'),
  earthShader: () => import('./Earth'),
  particlesAnimationShader: () => import('./ParticleAnimation'),
  morphingParticlesShader: () => import('./ParticleMorph'),
  gppuFlowFieldShader: () => import('./GppuFlowField'),
  wobblySphereShader: () => import('./WobblySphere'),
};
